const keywordResponses = [
  {
    keyword: "help",
    response: "How can I assist you?",
  },
  {
    keyword: "about",
    response: "This is a recipe generator chatbot.",
  },
  {
    keyword: "ingredients",
    response: "Please provide a list of ingredients separated by commas.",
  },

  {
    keyword: "gundruk ko achar",
    response: "<strong>Title:</strong> Gundruk ko Achar - Fermented Green Vegetable Pickle<br><br><strong>Ingredients:</strong> Gundruk (fermented leafy greens), tomatoes (chopped), onions (chopped), green chilies (sliced), garlic (minced), ginger (grated), mustard oil, turmeric powder, red chili powder, fenugreek seeds, cumin seeds, salt, lemon juice (optional)<br><strong>The Quantity of ingredients</strong><br>Varies depending on servings<br><br><strong>Instructions:</strong><br>1. Rinse the gundruk thoroughly under cold water to remove any excess salt.<br>2. Squeeze out the excess water from the gundruk and chop it into small pieces.<br>3. In a mixing bowl, combine the chopped gundruk with chopped tomatoes, onions, sliced green chilies, minced garlic, and grated ginger.<br>4. Heat mustard oil in a pan until it reaches smoking point, then remove it from heat and let it cool slightly.<br>5. Once the oil has cooled down a bit, add turmeric powder, red chili powder, fenugreek seeds, and cumin seeds to the oil. Stir well to infuse the flavors.<br>6. Pour the spiced oil over the gundruk mixture in the mixing bowl.<br>7. Add salt according to taste and mix all the ingredients thoroughly.<br>8. Optionally, add a splash of lemon juice for tanginess.<br>9. Transfer the Gundruk ko Achar to a clean, dry jar or airtight container.<br>10. Allow the flavors to meld together by letting the Achar sit at room temperature for a few hours.<br>11. Serve the Gundruk ko Achar as a spicy and tangy accompaniment to rice, dal, or other Nepali dishes.<br>12. Store any leftover Achar in the refrigerator for extended freshness.<br>13. Enjoy the unique and pungent flavors of homemade Gundruk ko Achar!"
},
{
  keyword:"gundruk",
  response:"<strong>:</strong> Gundruk - Fermented Leafy Greens<br><br><strong>Description:</strong> Gundruk is a traditional Nepali food made from fermenting leafy greens, such as mustard greens, radish leaves, or cauliflower leaves. The process of making gundruk involves wilting the greens, then fermenting them in airtight containers for several days. The fermentation process not only preserves the greens but also enhances their flavor, resulting in a tangy and slightly sour taste. Gundruk is a popular ingredient in Nepali cuisine and is used in various dishes, such as soups, curries, and pickles. It is also known for its nutritional benefits, as the fermentation process increases the bioavailability of certain nutrients. Gundruk is a staple food in many Nepali households and is enjoyed for its unique taste and health benefits."
},
{
  "keyword": "gundruk ko tarkari",
  "response": "<strong>:</strong> Gundruk ko Tarkari (Vegetable Curry with Fermented Greens)<br><br><strong>Ingredients:</strong> Mixed vegetables (potatoes, carrots, cauliflower, peas), onions, tomatoes, garlic, ginger, green chili (optional), gundruk (fermented greens), turmeric powder, cumin seeds, coriander powder, salt, cooking oil, cilantro leaves (for garnish)<br><strong>The Quantity of ingredients:</strong> Varies depending on servings<br><br><strong>Instructions:</strong><ol><li>Heat oil in a pan and add cumin seeds. Allow them to splutter.</li><li>Saute chopped onions until golden brown.</li><li>Add minced garlic, grated ginger, and chopped green chili. Saute for a minute.</li><li>Throw in chopped tomatoes and cook until they soften.</li><li>Season with turmeric powder, coriander powder, and salt. Stir well.</li><li>Add chopped mixed vegetables and gundruk to the pan. Mix thoroughly.</li><li>Pour in a little water, cover, and simmer until vegetables are tender.</li><li>Adjust seasoning if needed. Garnish with cilantro leaves.</li><li>Serve hot with rice or roti.</li></ol><br>Adjust ingredients and spices according to taste preferences. Enjoy your Gundruk ko Tarkari!"
},


  {
    keyword: "Ghonghi",
    response:
      "<strong>:</strong> Ghonghi - Morel Mushrooms<br><br><strong>Description:</strong> Ghonghi, also known as Morel mushrooms, are a highly prized edible wild mushroom found in various regions, including the Himalayan regions of Nepal. They are characterized by their distinctive honeycomb-like caps and hollow stems. Ghonghi mushrooms are renowned for their earthy flavor and meaty texture, making them a sought-after ingredient in Nepali cuisine, particularly during the spring season when they are in abundance. These mushrooms are used in a variety of dishes such as soups, curries, stir-fries, and omelets, adding depth and richness to the flavors.",
  },
  {
    keyword: "momo",
    response:
      "<strong>:</strong> Momo<br><br><strong>Ingredients:</strong><br>- 250g ground chicken or beef<br>- 1 onion, finely chopped<br>- 2 cloves garlic, minced<br>- 1-inch ginger, minced<br>- 2 tablespoons cilantro, chopped<br>- 1 teaspoon cumin powder<br>- 1 teaspoon coriander powder<br>- 1/2 teaspoon turmeric powder<br>- 1/2 teaspoon chili powder (adjust to taste)<br>- Salt to taste<br>- 1 package dumpling wrappers<br><br><strong>Dipping Sauce:</strong><br>- 2 tablespoons soy sauce<br>- 1 tablespoon vinegar<br>- 1 teaspoon sesame oil<br>- 1 teaspoon chili flakes<br><br><strong>Instructions:</strong><br><ol><li>In a mixing bowl, combine ground meat, chopped onion, minced garlic, minced ginger, chopped cilantro, cumin powder, coriander powder, turmeric powder, chili powder, and salt. Mix well.</li><li>Take a dumpling wrapper and place a spoonful of the meat mixture in the center.</li><li>Moisten the edges of the wrapper with water, then fold and pleat to seal the momo. Repeat with remaining wrappers and filling.</li><li>Steam the momo in a steamer for 10-12 minutes or until cooked through.</li><li>While momo is steaming, prepare the dipping sauce by combining soy sauce, vinegar, sesame oil, and chili flakes in a small bowl. Mix well.</li><li>Once the momo is cooked, serve hot with the dipping sauce on the side.</li></ol> ",
  },
  {
    keyword: "dal",
    response:
      "<strong>:</strong> Dal<br><br><strong>Ingredients:</strong><br>- 1 cup yellow lentils<br>- 4 cups water<br>- 1 teaspoon turmeric powder<br>- 1 teaspoon salt<br>- 2 tablespoons ghee or oil<br>- 1 teaspoon cumin seeds<br>- 1 teaspoon mustard seeds<br>- 1 onion, finely chopped<br>- 2 cloves garlic, minced<br>- 1-inch ginger, minced<br>- 2 tomatoes, chopped<br>- 1 teaspoon cumin powder<br>- 1 teaspoon coriander powder<br>- 1/2 teaspoon chili powder (adjust to taste)<br>- 1/2 teaspoon garam masala<br>- 2 tablespoons cilantro, chopped<br><br><strong>Instructions:</strong><br><ol><li>Rinse the lentils under running water until the water runs clear.</li><li>In a large pot, combine the lentils, water, turmeric powder, and salt. Bring to a boil, then reduce the heat and simmer for 20-25 minutes or until the lentils are soft.</li><li>While the lentils are cooking, heat ghee or oil in a pan over medium heat. Add cumin seeds and mustard seeds and cook until they start to splutter.</li><li>Add the chopped onion, minced garlic, and minced ginger. Cook until the onion is soft and translucent.</li><li>Add the chopped tomatoes, cumin powder, coriander powder, chili powder, and garam masala. Cook until the tomatoes are soft and the spices are fragrant.</li><li>Add the cooked lentils to the pan and mix well. Simmer for 5-10 minutes to allow the flavors to meld.</li><li>Garnish with chopped cilantro and serve hot with rice or roti.</li></ol>",
  },
  {
    keyword: "sel",
    response:
      "<strong>:</strong> Sel Roti<br><br><strong>Ingredients:</strong><br>- 2 cups rice flour<br>- 1/2 cup all-purpose flour<br>- 1/2 cup sugar<br>- 1/2 teaspoon cardamom powder<br>- 1/2 teaspoon baking powder<br>- 1 cup milk<br>- 1/2 cup water<br>- Oil for deep frying<br><br><strong>Instructions:</strong><br><ol><li>In a large bowl, combine rice flour, all-purpose flour, sugar, cardamom powder, and baking powder.</li><li>Add milk and water to the dry ingredients and mix well to form a smooth batter. The batter should be thick but pourable.</li><li>Heat oil in a deep frying pan over medium heat.</li><li>Pour the batter into a funnel or a squeeze bottle with a small opening. Hold the funnel or bottle over the hot oil and pour the batter in a circular motion to form a ring shape. You can also use a spoon to pour the batter into the oil.</li><li>Fry the sel roti until golden brown on both sides, turning once to ensure even cooking.</li><li>Remove the sel roti from the oil and drain on paper towels. Repeat with the remaining batter.</li><li>Serve the sel roti hot with tea or yogurt for breakfast or as a snack.</li></ol>",
  },
  {
    keyword: "yomari",
    response:
      "<strong>:</strong> Yomari<br><br><strong>Ingredients:</strong><br>- 2 cups rice flour<br>- 1 cup water<br>- 1 cup molasses<br>- 1 cup grated coconut<br>- 1/2 teaspoon cardamom powder<br>- 1/2 teaspoon ghee<br><br><strong>Instructions:</strong><br><ol><li>In a large bowl, combine rice flour and water to form a smooth dough. The dough should be soft and pliable.</li><li>In a separate bowl, combine molasses, grated coconut, and cardamom powder to make the filling.</li><li>Divide the dough into small balls and flatten them into discs. Place a spoonful of the filling in the center of each disc.</li><li>Fold the edges of the disc to form a half-moon shape, then pinch the edges to seal the yomari.</li><li>Steam the yomari in a steamer for 10-12 minutes or until cooked through.</li><li>Brush the steamed yomari with ghee to prevent sticking and to add flavor.</li><li>Serve the yomari hot as a dessert or snack.</li></ol>",
  },
  {
    keyword: "chatamari",
    response:
      "<strong>:</strong> Chatamari<br><br><strong>Ingredients:</strong><br>- 2 cups rice flour<br>- 1 cup water<br>- 1/2 cup minced meat (chicken, mutton, or buffalo)<br>- 1/2 cup chopped onion<br>- 1/2 cup chopped tomatoes<br>- 1/2 cup chopped green bell pepper<br>- 1/2 cup chopped cilantro<br>- 1/2 teaspoon cumin powder<br>- 1/2 teaspoon coriander powder<br>- 1/2 teaspoon chili powder (adjust to taste)<br>- Salt to taste<br>- Oil for cooking<br><br><strong>Instructions:</strong><br><ol><li>In a large bowl, combine rice flour and water to form a smooth batter. The batter should be thin and pourable.</li><li>In a separate bowl, combine minced meat, chopped onion, chopped tomatoes, chopped green bell pepper, chopped cilantro, cumin powder, coriander powder, chili powder, and salt to make the topping.</li><li>Heat a non-stick pan over medium heat and lightly grease with oil.</li><li>Pour a ladleful of the batter into the pan and spread it into a thin, round shape.</li><li>Sprinkle the topping over the batter and cook until the bottom is golden brown and crispy.</li><li>Repeat with the remaining batter and topping.</li><li>Serve the chatamari hot as a snack or appetizer.</li></ol>",
  },
  {
    keyword: "thukpa",
    response:
      "<strong>:</strong> Thukpa<br><br><strong>Ingredients:</strong> noodles, chicken or vegetable broth, chicken or vegetables (carrots, cabbage, spinach), onions, garlic, ginger, soy sauce, salt, pepper, chili flakes, vegetable oil<br><strong>The Quantity of ingredients</strong><br>200g noodles<br>4 cups chicken or vegetable broth<br>1 cup cooked chicken or mixed vegetables<br>1 onion, chopped<br>2 cloves garlic, minced<br>1-inch ginger, minced<br>2 tablespoons soy sauce<br>Salt and pepper to taste<br>Chili flakes to taste<br>2 tablespoons vegetable oil<br><br><strong>Instructions are:</strong> <br><ul ><li>Heat vegetable oil in a pot and sauté onions, garlic, and ginger until fragrant.</li><li>Add chicken or vegetables and cook until chicken is browned or vegetables are tender.</li><li>Pour in chicken or vegetable broth and bring to a boil.</li><li>Add noodles and cook according to package instructions.</li><li>Season with soy sauce, salt, pepper, and chili flakes to taste.</li><li>Serve hot.</li></ul>",
  },
  {
    keyword: "dhindo",
    response:
      '<strong>:</strong> Dhindo<br><br><strong>Ingredients:</strong> buckwheat flour, water<br><strong>The Quantity of ingredients</strong><br>2 cups buckwheat flour<br>4 cups water<br><br><strong>Instructions are:</strong> <br><ul style="list-style-type: disc;"><li>Boil water in a pot.</li><li>Add buckwheat flour gradually while stirring continuously to avoid lumps.</li><li>Keep stirring until the mixture thickens and forms a dough-like consistency.</li><li>Serve hot with your favorite side dish or curry.</li></ul>',
  },
  {
    keyword: "chukauni",
    response:
      '<strong>:</strong> Chukauni<br><br><strong>Ingredients:</strong> boiled potatoes, yogurt, mustard oil, fenugreek seeds, cumin seeds, turmeric powder, red chili powder, salt, green chilies, fresh coriander leaves<br><strong>The Quantity of ingredients</strong><br>4 boiled potatoes<br>1 cup yogurt<br>2 tablespoons mustard oil<br>1/2 teaspoon fenugreek seeds<br>1/2 teaspoon cumin seeds<br>1/2 teaspoon turmeric powder<br>1/2 teaspoon red chili powder<br>Salt to taste<br>2-3 green chilies, chopped<br>Fresh coriander leaves for garnish<br><br><strong>Instructions are:</strong> <br><ul style="list-style-type: disc;"><li>Mash boiled potatoes in a bowl.</li><li>Add yogurt and mix well to form a smooth consistency.</li><li>Heat mustard oil in a pan and add fenugreek seeds and cumin seeds. Fry until they crackle.</li><li>Add turmeric powder, red chili powder, and salt. Mix well.</li><li>Pour this mixture over the mashed potatoes and yogurt mixture.</li><li>Add chopped green chilies and mix thoroughly.</li><li>Garnish with fresh coriander leaves and serve as a side dish with rice or roti.</li></ul>',
  },
  {
    keyword: "spaghetti",
    response:
      '<strong>:</strong> Spaghetti<br><br><strong>Ingredients:</strong> spaghetti noodles, water, salt<br><strong>The Quantity of ingredients</strong><br>250g spaghetti noodles<br>4 cups water<br>Salt to taste<br><br><strong>Instructions are:</strong> <br><ul style="list-style-type: disc;"><li>Bring water to a boil in a large pot.</li><li>Add salt to the boiling water.</li><li>Add spaghetti noodles and cook according to package instructions or until al dente.</li><li>Drain the cooked spaghetti noodles.</li><li>Serve hot with your favorite pasta sauce and garnishes.</li></ul> ',
  },
  {
    keyword: "chowmein",
    response:
      '<strong>:</strong> Chowmein<br><br><strong>Ingredients:</strong> chowmein noodles, vegetables (carrots, cabbage, bell peppers), onions, garlic, ginger, soy sauce, salt, pepper, chili flakes, vegetable oil<br><strong>The Quantity of ingredients</strong><br>200g chowmein noodles<br>1 cup mixed vegetables (carrots, cabbage, bell peppers)<br>1 onion, sliced<br>2 cloves garlic, minced<br>1-inch ginger, minced<br>2 tablespoons soy sauce<br>Salt and pepper to taste<br>Chili flakes to taste<br>2 tablespoons vegetable oil<br><br><strong>Instructions are:</strong> <br><ul style="list-style-type: disc;"><li>Boil chowmein noodles according to package instructions. Drain and set aside.</li><li>Heat vegetable oil in a pan and sauté onions, garlic, and ginger until fragrant.</li><li>Add mixed vegetables and cook until tender.</li><li>Add cooked chowmein noodles and soy sauce. Toss to combine.</li><li>Season with salt, pepper, and chili flakes to taste.</li><li>Serve hot.</li></ul>',
  },
  {
    keyword: "achaar",
    response:
      '<strong>:</strong> Achaar<br><br><strong>Ingredients:</strong> vegetables (mango, lime, carrot, etc.), mustard oil, mustard seeds, fenugreek seeds, fennel seeds, nigella seeds, turmeric powder, red chili powder, salt, vinegar, sugar<br><strong>The Quantity of ingredients</strong><br>Assorted vegetables (e.g., 2 mangoes, 2 limes, 2 carrots)<br>1/2 cup mustard oil<br>2 tablespoons mustard seeds<br>1 tablespoon fenugreek seeds<br>1 tablespoon fennel seeds<br>1 tablespoon nigella seeds<br>1 teaspoon turmeric powder<br>2 tablespoons red chili powder (adjust to taste)<br>Salt to taste<br>1/2 cup vinegar<br>1/4 cup sugar (adjust to taste)<br><br><strong>Instructions are:</strong> <br><ul style="list-style-type: disc;"><li>Cut the vegetables (mangoes, limes, carrots, etc.) into small pieces.</li><li>Heat mustard oil in a pan until it reaches smoking point. Remove from heat and let it cool.</li><li>In a separate pan, dry roast mustard seeds, fenugreek seeds, ',
  },
  {
    keyword: "anarasa",
    response:
      '<strong>:</strong> Anarsa - Sweet Rice Fried Cookie<br><br><strong>Ingredients:</strong> rice flour, jaggery (or sugar), ghee (clarified butter), poppy seeds (optional), oil for frying<br><strong>The Quantity of ingredients</strong><br>2 cups rice flour<br>1 cup jaggery (or sugar), grated<br>1/4 cup ghee (clarified butter)<br>2 tablespoons poppy seeds (optional)<br>Oil for frying<br><br><strong>Instructions are:</strong> <br><ul style="list-style-type: disc;"><li>In a mixing bowl, combine rice flour and grated jaggery.</li><li>Add ghee gradually and mix well until it forms a dough-like consistency.</li><li>Cover the dough and let it rest for a few hours or overnight.</li><li>Divide the dough into small portions and shape them into flat discs or any desired shape.</li><li>Sprinkle poppy seeds (if using) on top of the shaped dough.</li><li>Heat oil in a frying pan or kadhai over medium heat.</li><li>Fry the shaped dough in batches until golden brown and crispy on both sides.</li><li>Remove from the oil and drain excess oil using paper towels.</li><li>Let the Anarsa cool completely before serving.</li><li>Enjoy this sweet rice fried cookie as a snack or dessert!</li></ul>',
  },
  {
    keyword: "kheer",
    response:
      '<strong>:</strong> Kheer - Rice Pudding<br><br><strong>Ingredients:</strong> rice, milk, sugar, cardamom, saffron, nuts (almonds, cashews, raisins), ghee (clarified butter)<br><strong>The Quantity of ingredients</strong><br>1/2 cup rice<br>4 cups milk<br>1/2 cup sugar<br>1/2 teaspoon cardamom powder<br>A pinch of saffron<br>1/4 cup mixed nuts (almonds, cashews, raisins)<br>1 tablespoon ghee (clarified butter)<br><br><strong>Instructions are:</strong> <br><ul style="list-style-type: disc;"><li>Wash and soak rice in water for 30 minutes.</li><li>Drain the rice and set aside.</li><li>In a heavy-bottomed pan, bring milk to a boil.</li><li>Add the soaked rice to the boiling milk and cook on low heat, stirring occasionally.</li><li>When the rice is cooked and the milk has thickened, add sugar and mix well.</li><li>Add cardamom powder and saffron to the kheer and mix well.</li><li>In a separate pan, heat ghee and fry the mixed nuts until golden brown.</li><li>Add the fried nuts to the kheer and mix well.</li><li>Remove from heat and let the kheer cool to room temperature.</li><li>Refrigerate the kheer for a few hours before serving.</li><li>Enjoy this creamy rice pudding as a dessert!</li></ul>',
  },
  {
    keyword: "laddu",
    response:
      '<strong>:</strong> Laddu - Sweet Balls<br><br><strong>Ingredients:</strong> chickpea flour, ghee (clarified butter), sugar, cardamom, nuts (almonds, cashews, raisins)<br><strong>The Quantity of ingredients</strong><br>2 cups chickpea flour<br>1 cup ghee (clarified butter)<br>1 cup sugar<br>1/2 teaspoon cardamom powder<br>1/4 cup mixed nuts (almonds, cashews, raisins)<br><br><strong>Instructions are:</strong> <br><ul style="list-style-type: disc;"><li>In a heavy-bottomed pan, dry roast chickpea flour on low heat until fragrant and golden brown.</li><li>Add ghee to the roasted chickpea flour and mix well.</li><li>Continue to cook the mixture on low heat, stirring continuously, until it turns a few shades darker and releases a nutty aroma.</li><li>Remove from heat and let the mixture cool slightly.</li><li>Add sugar and cardamom powder to the mixture and mix well.</li><li>In a separate pan, heat ghee and fry the mixed nuts until golden brown.</li><li>Add the fried nuts to the mixture and mix well.</li><li>While the mixture is still warm, shape it into small balls or laddus.</li><li>Let the laddus cool completely before serving.</li><li>Enjoy these sweet balls as a dessert or snack!</li></ul>',
  },
  {
    keyword: "samosa",
    response:
      '<strong>:</strong> Samosa<br><br><strong>Ingredients:</strong> all-purpose flour, oil, potatoes, peas, onions, garlic, ginger, green chilies, coriander leaves, cumin seeds, coriander seeds, turmeric powder, red chili powder, garam masala, salt<br><strong>The Quantity of ingredients</strong><br>2 cups all-purpose flour<br>1/4 cup oil<br>2 large potatoes, boiled and mashed<br>1/2 cup peas<br>1 onion, finely chopped<br>2 cloves garlic, minced<br>1-inch ginger, minced<br>2-3 green chilies, chopped<br>2 tablespoons coriander leaves, chopped<br>1 teaspoon cumin seeds<br>1 teaspoon coriander seeds<br>1/2 teaspoon turmeric powder<br>1 teaspoon red chili powder<br>1 teaspoon garam masala<br>Salt to taste<br>Oil for deep frying<br><br><strong>Instructions are:</strong> <br><ul style="list-style-type: disc;"><li>In a mixing bowl, combine all-purpose flour and oil. Mix well to form a crumbly texture.</li><li>Add water gradually and knead the mixture into a smooth dough. Cover and let it rest for 30 minutes.</li><li>In a pan, heat oil and add cumin seeds and coriander seeds. Fry until they start to splutter.</li><li>Add chopped onions, minced garlic, minced ginger, and chopped green chilies. Cook until the onions are soft and translucent.</li><li>Add mashed potatoes, peas, coriander leaves, turmeric powder, red chili powder, garam masala, and salt. Mix well and cook for a few minutes.</li><li>Divide the dough into small balls and roll each ball into a thin disc.</li><li>Cut the disc in half to form two semi-circles.</li><li>Take one semi-circle and form a cone shape by folding and sealing the edges with water.</li><li>Fill the cone with the potato and pea mixture and seal the open end with water.</li><li>Repeat with the remaining dough and filling.</li><li>Heat oil in a deep frying pan over medium heat.</li><li>Fry the samosas until golden brown and crispy on all sides.</li><li>Remove from the oil and drain excess oil using paper towels.</li><li>Serve the samosas hot with your favorite chutney or sauce.</li></ul>',
  },
  {
    keyword: "bambaisan",
    response:
      '<strong>:</strong> Bambaisan - Milk-Based Sweet from Ilam District<br><br><strong>Ingredients:</strong> milk, sugar, cardamom powder, saffron (optional), nuts (almonds, pistachios, cashews), ghee (clarified butter)<br><strong>The Quantity of ingredients</strong><br>1 liter milk<br>1 cup sugar<br>1 teaspoon cardamom powder<br>A pinch of saffron (optional)<br>Assorted nuts (almonds, pistachios, cashews), chopped<br>Ghee (clarified butter) for greasing<br><br><strong>Instructions are:</strong> <br><ul style="list-style-type: disc;"><li>In a heavy-bottomed pan, bring the milk to a boil over medium heat.</li><li>Reduce the heat to low and simmer the milk, stirring occasionally, until it reduces to about half its volume.</li><li>Add sugar, cardamom powder, and saffron (if using) to the reduced milk.</li><li>Continue to simmer the mixture until it thickens to a pudding-like consistency, stirring frequently to prevent burning.</li><li>Once the mixture thickens, add chopped nuts and mix well.</li><li>Grease a tray or plate with ghee and pour the thickened milk mixture into it, spreading it evenly.</li><li>Allow the mixture to cool and set at room temperature for a few hours or refrigerate until firm.</li><li>Once set, cut the Bambaisan into desired shapes and serve as a delicious dessert or sweet treat!</li></ul>',
  },
  {
    keyword: "sukuti",
    response:
      '<strong>:</strong> Sukuti - Dried Meat<br><br><strong>Ingredients:</strong> meat (buffalo, goat, or lamb), salt, spices (cumin, coriander, turmeric, chili powder), oil<br><strong>The Quantity of ingredients</strong><br>1 kg meat (buffalo, goat, or lamb)<br>2 tablespoons salt<br>1 tablespoon cumin powder<br>1 tablespoon coriander powder<br>1 teaspoon turmeric powder<br>1 tablespoon chili powder (adjust to taste)<br>2 tablespoons oil<br><br><strong>Instructions are:</strong> <br><ul style="list-style-type: disc;"><li>Cut the meat into thin strips or cubes.</li><li>Combine the meat with salt, cumin powder, coriander powder, turmeric powder, and chili powder in a bowl. Mix well to coat the meat evenly with the spices.</li><li>Heat oil in a pan and add the spiced meat. Cook over low heat, stirring occasionally, until the meat is dry and crispy.</li><li>Remove from heat and let the Sukuti cool completely.</li><li>Store the Sukuti in an airtight container and enjoy it as a snack or side dish with rice or roti!</li></ul>',
  },
  {
    keyword: "kodo",
    response:
      '<strong>:</strong> Kodo Ko Roti - Millet Flatbread<br><br><strong>Ingredients:</strong> kodo millet flour, water, salt<br><strong>The Quantity of ingredients</strong><br>2 cups kodo millet flour<br>1 cup water<br>Salt to taste<br><br><strong>Instructions are:</strong> <br><ul style="list-style-type: disc;"><li>In a mixing bowl, combine kodo millet flour and salt.</li><li>Add water gradually and knead the mixture into a smooth dough.</li><li>Divide the dough into small balls and roll each ball into a thin disc.</li><li>Heat a non-stick pan over medium heat and cook the roti on both sides until golden brown spots appear.</li><li>Remove from the pan and serve the Kodo Ko Roti hot with your favorite curry or side dish.</li></ul>',
  },
  {
    keyword: "bhatmaas",
    response:
      '<strong>:</strong> Bhatmaas - Fried Lentils<br><br><strong>Ingredients:</strong> lentils (black gram or green gram), oil, salt, spices (cumin, coriander, turmeric, chili powder)<br><strong>The Quantity of ingredients</strong><br>1 cup lentils (black gram or green gram)<br>Oil for deep frying<br>Salt to taste<br>1 teaspoon cumin powder<br>1 teaspoon coriander powder<br>1/2 teaspoon turmeric powder<br>1/2 teaspoon chili powder (adjust to taste)<br><br><strong>Instructions are:</strong> <br><ul style="list-style-type: disc;"><li>Wash and soak the lentils in water for a few hours or overnight.</li><li>Drain the lentils and spread them on a clean cloth to dry completely.</li><li>Heat oil in a deep frying pan over medium heat.</li><li>Add the dried lentils to the hot oil and fry until golden brown and crispy.</li><li>Remove from the oil and drain excess oil using paper towels.</li><li>Season the fried lentils with salt, cumin powder, coriander powder, turmeric powder, and chili powder.</li><li>Let the Bhatmaas cool completely before serving.</li><li>Enjoy these crispy fried lentils as a snack or side dish!</li></ul>',
  },
  {
    keyword: "kochila",
    response:
      '<strong>:</strong> Kochila<br><br><strong>Ingredients:</strong> taro roots (kochu), chickpea flour, rice flour, turmeric powder, red chili powder, salt, water, oil for frying<br><strong>The Quantity of ingredients</strong><br>4-5 taro roots (kochu)<br>1 cup chickpea flour<br>1/4 cup rice flour<br>1/2 teaspoon turmeric powder<br>1 teaspoon red chili powder (adjust to taste)<br>Salt to taste<br>Water as needed<br>Oil for frying<br><br><strong>Instructions are:</strong> <br><ul style="list-style-type: disc;"><li>Peel and slice the taro roots (kochu) into thin rounds.</li><li>In a mixing bowl, combine chickpea flour, rice flour, turmeric powder, red chili powder, and salt.</li><li>Add water gradually and mix well to form a smooth batter. The batter should be thick but pourable.</li><li>Heat oil in a deep frying pan over medium heat.</li><li>Dip the taro slices in the batter and carefully drop them into the hot oil.</li><li>Fry the Kochila until golden brown and crispy on both sides.</li><li>Remove from the oil and drain excess oil using paper towels.</li><li>Enjoy the Kochila hot as a snack or side dish!</li></ul>',
  },
  {
    keyword: "buffalo curd",
    response:
      '<strong>:</strong> Buffalo Curd<br><br><strong>Ingredients:</strong> buffalo milk, curd culture<br><strong>The Quantity of ingredients</strong><br>1 liter buffalo milk<br>2 tablespoons curd culture<br><br><strong>Instructions are:</strong> <br><ul style="list-style-type: disc;"><li>Boil the buffalo milk and let it cool to room temperature.</li><li>Add curd culture to the milk and mix well.</li><li>Transfer the milk to a clean container and cover it with a lid or cloth.</li><li>Keep the container in a warm place for 6-8 hours or until the milk sets into curd.</li><li>Once the curd is set, refrigerate it for a few hours before serving.</li><li>Enjoy the creamy and tangy buffalo curd as a dessert or snack!</li></ul>',
  },
  {
    keyword: "yogurt",
    response:
      '<strong>:</strong> Yogurt<br><br><strong>Ingredients:</strong> milk, curd culture<br><strong>The Quantity of ingredients</strong><br>1 liter milk<br>2 tablespoons curd culture<br><br><strong>Instructions are:</strong> <br><ul style="list-style-type: disc;"><li>Boil the milk and let it cool to room temperature.</li><li>Add curd culture to the milk and mix well.</li><li>Transfer the milk to a clean container and cover it with a lid or cloth.</li><li>Keep the container in a warm place for 6-8 hours or until the milk sets into yogurt.</li><li>Once the yogurt is set, refrigerate it for a few hours before serving.</li><li>Enjoy the creamy and tangy yogurt as a dessert or snack!</li></ul>',
  },
  {
    keyword: "bhakka",
    response:
      '<strong>:</strong> Bhakka<br><br><strong>Ingredients:</strong> rice flour, water, salt<br><strong>The Quantity of ingredients</strong><br>2 cups rice flour<br>4 cups water<br>Salt to taste<br><br><strong>Instructions are:</strong> <br><ul style="list-style-type: disc;"><li>In a large pot, bring water to a boil.</li><li>Add salt to the boiling water.</li><li>Gradually add rice flour to the boiling water while stirring continuously to prevent lumps from forming.</li><li>Reduce the heat to low and continue stirring the mixture until it thickens and forms a smooth dough-like consistency.</li><li>Remove the pot from the heat and let the dough cool slightly.</li><li>Divide the dough into small portions and shape them into round discs or any desired shape.</li><li>Steam the shaped dough discs in a steamer for about 20-25 minutes or until cooked through.</li><li>Once cooked, remove the Bhakka from the steamer and let them cool slightly before serving.</li><li>Serve the warm Bhakka with your favorite curry or chutney.</li><li>Enjoy this traditional rice flour delicacy!</li></ul>',
  },
  {
    keyword: "bigauti",
    response:
      "<strong>:</strong> Bigauti - Sweet made from Cow's Colostrum Milk<br><br><strong>Ingredients:</strong> cow's colostrum milk, sugar, cardamom powder, ghee (clarified butter), nuts (almonds, cashews, pistachios)<br><strong>The Quantity of ingredients</strong><br>1 cup cow's colostrum milk<br>1/2 cup sugar (adjust to taste)<br>1/2 teaspoon cardamom powder<br>2 tablespoons ghee (clarified butter)<br>Assorted nuts (almonds, cashews, pistachios), chopped<br><br><strong>Instructions are:</strong> <br><ul style=\"list-style-type: disc;\"><li>In a heavy-bottomed pan, heat ghee over low heat.</li><li>Add cow's colostrum milk to the pan and stir continuously to prevent burning.</li><li>Once the milk starts to thicken, add sugar and cardamom powder.</li><li>Continue stirring until the mixture thickens further and starts to leave the sides of the pan.</li><li>Add chopped nuts and mix well.</li><li>Remove the mixture from the heat and let it cool for a few minutes.</li><li>Grease a plate or tray with ghee and pour the thickened milk mixture into it, spreading it evenly.</li><li>Allow the mixture to set at room temperature for a few hours or refrigerate until firm.</li><li>Once set, cut the Bigauti into small pieces or desired shapes.</li><li>Serve and enjoy this unique and delicious sweet made from cow's colostrum milk!</li></ul>",
  },
  {
    keyword: "bunga",
    response:
      '<strong>:</strong> Bunga ko Achar - Salad made from Banana Flower<br><br><strong>Ingredients:</strong> banana flower, mustard oil, fenugreek seeds, cumin seeds, turmeric powder, red chili powder, salt, lemon juice<br><strong>The Quantity of ingredients</strong><br>1 banana flower<br>2 tablespoons mustard oil<br>1/2 teaspoon fenugreek seeds<br>1/2 teaspoon cumin seeds<br>1/2 teaspoon turmeric powder<br>1 teaspoon red chili powder (adjust to taste)<br>Salt to taste<br>Lemon juice to taste<br><br><strong>Instructions are:</strong> <br><ul style="list-style-type: disc;"><li>Remove the outer layers of the banana flower until you reach the tender, pale-colored inner layers.</li><li>Finely chop the tender inner layers of the banana flower and soak them in water with a little lemon juice to prevent discoloration.</li><li>In a pan, heat mustard oil and add fenugreek seeds and cumin seeds. Fry until they crackle.</li><li>Add turmeric powder and red chili powder to the oil and stir well.</li><li>Add the chopped banana flower to the pan and sauté for a few minutes until the raw smell disappears.</li><li>Season with salt and cook until the banana flower is tender.</li><li>Remove from heat and let it cool to room temperature.</li><li>Once cooled, squeeze some lemon juice over the banana flower mixture and mix well.</li><li>Transfer the Bunga ko Achar to a serving bowl and serve as a salad or side dish with rice or roti.</li><li>Enjoy the unique and flavorful salad made from banana flower!</li></ul>',
  },
  {
    keyword: "chaat",
    response:
      "<strong>:</strong> Chaat<br><br><strong>Ingredients:</strong> potatoes, chickpeas, onions, tomatoes, green chilies, tamarind chutney, mint chutney, yogurt, chaat masala, cumin powder, red chili powder, coriander leaves, sev (crispy chickpea noodles), papdi (crispy crackers)<br><strong>The Quantity of ingredients</strong><br>2 potatoes, boiled and cubed<br>1 cup chickpeas, boiled<br>1 onion, finely chopped<br>1 tomato, finely chopped<br>2-3 green chilies, finely chopped<br>Tamarind chutney to taste<br>Mint chutney to taste<br>1/2 cup yogurt<br>1 teaspoon chaat masala<br>1/2 teaspoon cumin powder<br>1/2 teaspoon red chili powder<br>2 tablespoons coriander leaves, chopped<br>Sev (crispy chickpea noodles) for garnish<br>Papdi (crispy crackers) for garnish<br><br><strong>Instructions are:</strong> <br><ul style='list-style-type: disc;'><li>In a large mixing bowl, combine boiled potatoes, chickpeas, onions, tomatoes, and green chilies.</li><li>Add tamarind chutney and mint chutney according to taste preferences.</li><li>Drizzle yogurt over the mixture and sprinkle chaat masala, cumin powder, and red chili powder.</li><li>Garnish with chopped coriander leaves, sev, and papdi.</li><li>Toss the mixture gently until all the ingredients are well combined.</li><li>Serve immediately and enjoy the delicious flavors of Chaat!</li></ul>",
  },
  {
    keyword: "chatamari",
    response:
      "<strong>:</strong> Chatamari<br><br><strong>Ingredients:</strong> rice flour, water, minced meat (chicken, lamb, or buffalo), onions, tomatoes, green chilies, ginger-garlic paste, cumin powder, turmeric powder, salt, vegetable oil<br><strong>The Quantity of ingredients</strong><br>2 cups rice flour<br>3 cups water<br>1 cup minced meat (chicken, lamb, or buffalo)<br>1 onion, finely chopped<br>1 tomato, finely chopped<br>2-3 green chilies, finely chopped<br>1 teaspoon ginger-garlic paste<br>1 teaspoon cumin powder<br>1/2 teaspoon turmeric powder<br>Salt to taste<br>Vegetable oil for frying<br><br><strong>Instructions are:</strong> <br><ul style='list-style-type: disc;'><li>In a mixing bowl, combine rice flour and water to make a smooth batter. Let it rest for about 30 minutes.</li><li>In a separate bowl, mix minced meat, onions, tomatoes, green chilies, ginger-garlic paste, cumin powder, turmeric powder, and salt to make the topping.</li><li>Heat a non-stick pan over medium heat and brush with vegetable oil.</li><li>Pour a ladleful of the rice flour batter onto the pan and spread it evenly to make a thin pancake.</li><li>Spread a layer of the meat topping over the pancake.</li><li>Cover and cook until the bottom is golden brown and the topping is cooked.</li><li>Repeat the process with the remaining batter and topping.</li><li>Serve hot with your favorite sauce or chutney.</li><li>Enjoy the delicious Nepali specialty, Chatamari!</li></ul>",
  },
  {
    keyword: "chatpate",
    response:
      "<strong>:</strong> Chatpate<br><br><strong>Ingredients:</strong> puffed rice (murmura), chopped onions, chopped tomatoes, chopped cucumber, chopped boiled potatoes, chopped green chilies, chopped cilantro (coriander leaves), roasted peanuts, lemon juice, tamarind chutney, mint chutney, chaat masala, salt<br><strong>The Quantity of ingredients</strong><br>2 cups puffed rice (murmura)<br>1 onion, finely chopped<br>1 tomato, finely chopped<br>1 cucumber, finely chopped<br>1 boiled potato, finely chopped<br>2-3 green chilies, finely chopped<br>2 tablespoons cilantro (coriander leaves), chopped<br>1/4 cup roasted peanuts<br>Juice of 1 lemon<br>Tamarind chutney to taste<br>Mint chutney to taste<br>1 teaspoon chaat masala<br>Salt to taste<br><br><strong>Instructions are:</strong> <br><ul style='list-style-type: disc;'><li>In a large mixing bowl, combine puffed rice, chopped onions, tomatoes, cucumber, boiled potatoes, green chilies, cilantro, and roasted peanuts.</li><li>Add lemon juice, tamarind chutney, mint chutney, chaat masala, and salt according to taste preferences.</li><li>Toss the mixture gently until all the ingredients are well combined.</li><li>Adjust the seasoning if necessary.</li><li>Serve immediately and enjoy the tangy and spicy flavors of Chatpate!</li></ul>",
  },
  {
    keyword: "chhurpi",
    response:
      "<strong>:</strong> Chhurpi - Traditional Himalayan Cheese<br><br><strong>Ingredients:</strong> yak milk or cow milk<br><strong>The Quantity of ingredients</strong><br>Varies depending on the quantity of milk used<br><br><strong>Instructions:</strong><br>1. Heat yak milk or cow milk in a large pot over medium heat until it reaches a near-boiling temperature.<br>2. Add a coagulant like lemon juice or vinegar to the hot milk to curdle it. Stir gently until the milk separates into curds and whey.<br>3. Line a colander with cheesecloth and pour the curdled milk into it to strain out the whey. Let it drain for about 30 minutes.<br>4. Once most of the whey has drained off, gather the corners of the cheesecloth and tie them together to form a pouch. Hang the pouch to drain further for several hours or overnight.<br>5. After the whey has completely drained, untie the cheesecloth and transfer the solid curds to a clean surface.<br>6. Press the curds firmly to remove excess moisture. Traditionally, this is done by placing a heavy weight on top of the curds for several hours.<br>7. Once the curds have been pressed, they are left to air dry for several days or weeks until they harden into chhurpi.<br>8. Once dried and hardened, chhurpi can be stored in a cool, dry place for extended periods.<br>9. Chhurpi can be grated, chewed, or melted and used in various dishes as desired, adding a unique flavor and texture to Himalayan cuisine.",
  },
  {
    keyword: "chicken curry",
    response:
      "<strong>:</strong> Chicken Curry<br><br><strong>Ingredients:</strong> chicken pieces, onions, tomatoes, garlic, ginger, green chilies, yogurt, vegetable oil, spices (such as cumin, coriander, turmeric, chili powder, garam masala), salt, cilantro leaves<br><strong>The Quantity of ingredients</strong><br>500g chicken pieces<br>2 onions, finely chopped<br>2 tomatoes, finely chopped<br>4 cloves garlic, minced<br>1-inch ginger, grated<br>2-3 green chilies, slit lengthwise<br>1/2 cup yogurt<br>3 tablespoons vegetable oil<br>Spices: 1 teaspoon cumin seeds, 1 teaspoon coriander powder, 1/2 teaspoon turmeric powder, 1 teaspoon chili powder (adjust to taste), 1 teaspoon garam masala<br>Salt to taste<br>Handful of cilantro leaves, chopped, for garnish<br><br><strong>Instructions are:</strong> <br><ul style='list-style-type: disc;'><li>Heat vegetable oil in a large skillet or pot over medium heat.</li><li>Add cumin seeds and let them sizzle for a few seconds.</li><li>Add chopped onions and sauté until golden brown.</li><li>Add minced garlic, grated ginger, and slit green chilies. Sauté for another minute.</li><li>Add chopped tomatoes and cook until they turn soft and oil starts to separate.</li><li>Now add the chicken pieces to the skillet and mix well with the onion-tomato mixture.</li><li>Add coriander powder, turmeric powder, chili powder, and salt. Stir to coat the chicken pieces evenly with the spices.</li><li>Cover and cook the chicken until it is almost done, stirring occasionally.</li><li>Once the chicken is almost cooked, add yogurt to the skillet and mix well. Cook for another 5-7 minutes until the chicken is tender and the gravy thickens.</li><li>Sprinkle garam masala over the chicken curry and give it a final stir.</li><li>Garnish with chopped cilantro leaves before serving.</li><li>Serve hot with rice, naan, or roti. Enjoy your delicious Chicken Curry!</li></ul>",
  },
  {
    keyword: "choop",
    response:
      "Choop is a powdered mixture commonly found in Nepali cuisine, consisting of various ingredients including sesame seeds (Til), roasted soybeans (Silam), roasted finger millet (Alas), roasted buckwheat (Filunge), and Sichuan pepper (Timmur). This mixture is often used as a seasoning or flavoring agent in different dishes. To prepare Choop, each ingredient is roasted separately and then ground into a fine powder. Once all the ingredients are powdered, they are mixed together in the desired proportions. Choop adds a unique flavor and texture to a variety of Nepali dishes, including snacks, soups, and curries.",
  },
  {
    keyword: "chutney",
    response:
      "<strong>:</strong> Chutney<br><br><strong>Ingredients:</strong> fruits or vegetables (such as mangoes, tomatoes, apples, dates, mint leaves, coriander leaves), vinegar, sugar, salt, spices (such as cumin, coriander, chili powder), garlic, ginger<br><strong>The Quantity of ingredients</strong><br>Varies depending on the type of chutney and personal preference<br><br><strong>Instructions:</strong> <br><ul style='list-style-type: disc;'><li>Wash and prepare the fruits or vegetables by peeling, chopping, or slicing them as needed.</li><li>In a saucepan, combine the chopped fruits or vegetables with vinegar, sugar, salt, and spices.</li><li>Add garlic and ginger for extra flavor, if desired.</li><li>Bring the mixture to a simmer over medium heat, stirring occasionally to prevent sticking or burning.</li><li>Cook until the fruits or vegetables are soft and the mixture has thickened to a chutney-like consistency.</li><li>Remove from heat and let the chutney cool to room temperature.</li><li>Transfer the chutney to sterilized jars or containers for storage.</li><li>Chutney can be stored in the refrigerator for several weeks or preserved using canning methods for longer shelf life.</li><li>Serve chutney as a condiment or accompaniment to various dishes, such as samosas, pakoras, or grilled meats.</li><li>Enjoy the flavorful and versatile taste of homemade chutney!</li></ul>",
  },
  {
    keyword: "dal",
    response:
      "<strong>:</strong> Dal (Lentil Curry)<br><br><strong>Ingredients:</strong> lentils (such as red lentils, yellow lentils, or split mung beans), onions, tomatoes, garlic, ginger, green chilies, turmeric powder, cumin seeds, coriander powder, garam masala, vegetable oil, salt, cilantro leaves<br><strong>The Quantity of ingredients</strong><br>1 cup lentils (any variety)<br>1 onion, finely chopped<br>2 tomatoes, finely chopped<br>3 cloves garlic, minced<br>1-inch ginger, grated<br>2-3 green chilies, slit lengthwise<br>1/2 teaspoon turmeric powder<br>1 teaspoon cumin seeds<br>1 teaspoon coriander powder<br>1/2 teaspoon garam masala<br>2 tablespoons vegetable oil<br>Salt to taste<br>Handful of cilantro leaves, chopped, for garnish<br><br><strong>Instructions are:</strong> <br><ul style='list-style-type: disc;'><li>Rinse the lentils thoroughly under running water and drain.</li><li>In a pressure cooker or pot, combine lentils, chopped onions, tomatoes, minced garlic, grated ginger, slit green chilies, turmeric powder, cumin seeds, coriander powder, garam masala, vegetable oil, and salt.</li><li>Add enough water to cover the lentils by about 1 inch.</li><li>Cook the lentils until soft and tender. If using a pressure cooker, cook for about 3-4 whistles; if using a pot, cook for about 20-25 minutes or until the lentils are cooked through.</li><li>Once the lentils are cooked, mash them lightly using the back of a spoon or a potato masher to achieve a creamy consistency.</li><li>Adjust the consistency of the dal by adding more water if necessary.</li><li>Check for seasoning and adjust salt and spices according to taste.</li><li>Simmer the dal for a few more minutes to allow the flavors to meld together.</li><li>Garnish with chopped cilantro leaves before serving.</li><li>Serve hot with rice or roti. Enjoy the comforting and nutritious dal!</li></ul>",
  },
  {
    keyword: "dalbhat",
    response:
      "<strong>:</strong> Dal Bhat (Rice and Lentil Curry)<br><br><strong>Ingredients:</strong> lentils (such as red lentils, yellow lentils, or split mung beans), rice, onions, tomatoes, garlic, ginger, green chilies, turmeric powder, cumin seeds, coriander powder, garam masala, vegetable oil, salt, cilantro leaves<br><strong>The Quantity of ingredients</strong><br>1 cup lentils (any variety)<br>1 cup rice<br>1 onion, finely chopped<br>2 tomatoes, finely chopped<br>3 cloves garlic, minced<br>1-inch ginger, grated<br>2-3 green chilies, slit lengthwise<br>1/2 teaspoon turmeric powder<br>1 teaspoon cumin seeds<br>1 teaspoon coriander powder<br>1/2 teaspoon garam masala<br>2 tablespoons vegetable oil<br>Salt to taste<br>Handful of cilantro leaves, chopped, for garnish<br><br><strong>Instructions are:</strong> <br><ul style='list-style-type: disc;'><li>Rinse the lentils thoroughly under running water and drain.</li><li>In a pressure cooker or pot, combine lentils, chopped onions, tomatoes, minced garlic, grated ginger, slit green chilies, turmeric powder, cumin seeds, coriander powder, garam masala, vegetable oil, and salt.</li><li>Add enough water to cover the lentils by about 1 inch.</li><li>Cook the lentils until soft and tender. If using a pressure cooker, cook for about 3-4 whistles; if using a pot, cook for about 20-25 minutes or until the lentils are cooked through.</li><li>Once the lentils are cooked, mash them lightly using the back of a spoon or a potato masher to achieve a creamy consistency.</li><li>Meanwhile, rinse the rice under running water until the water runs clear. Cook the rice in a separate pot according to package instructions.</li><li>Check for seasoning and adjust salt and spices according to taste.</li><li>Simmer the dal for a few more minutes to allow the flavors to meld together.</li><li>Garnish with chopped cilantro leaves before serving.</li><li>Serve hot with rice. Enjoy the quintessential Nepali meal, Dal Bhat!</li></ul>",
  },
  {
    keyword: "dhikri",
    response:
      "<strong>:</strong> Dhikri - Traditional Tharu Dumplings<br><br><strong>Ingredients:</strong> rice flour, water, salt<br><strong>The Quantity of ingredients</strong><br>2 cups rice flour<br>1 cup water (approximately)<br>Salt to taste<br><br><strong>Instructions:</strong> <br><ul style='list-style-type: disc;'><li>In a mixing bowl, combine rice flour and salt.</li><li>Add water gradually and knead the mixture to form a smooth, pliable dough. The dough should be firm enough to hold its shape but not too dry.</li><li>Divide the dough into small portions and roll them between your palms to form small round dumplings or balls.</li><li>Bring a pot of water to a boil and add salt to the water.</li><li>Gently drop the dumplings into the boiling water, ensuring they are fully submerged.</li><li>Cook the dumplings for about 10-15 minutes or until they float to the surface and are cooked through.</li><li>Once cooked, remove the dumplings from the water using a slotted spoon and drain any excess water.</li><li>Serve hot Dhikri with your choice of accompaniments such as lentil curry, vegetables, or meat curries.</li><li>Enjoy this traditional Tharu dish as a comforting and wholesome meal!</li></ul>",
  },
  {
    keyword: "cauliflower",
    response:
      "<strong>:</strong> Fried Cauliflower<br><br><strong>Ingredients:</strong> cauliflower florets, all-purpose flour, cornstarch, garlic powder, onion powder, paprika, salt, black pepper, water, vegetable oil for frying<br><strong>The Quantity of ingredients</strong><br>1 medium cauliflower, cut into florets<br>1 cup all-purpose flour<br>1/4 cup cornstarch<br>1 teaspoon garlic powder<br>1 teaspoon onion powder<br>1/2 teaspoon paprika (adjust to taste)<br>Salt and black pepper to taste<br>1/2 cup water (adjust as needed)<br>Vegetable oil for frying<br><br><strong>Instructions are:</strong> <br><ul style='list-style-type: disc;'><li>In a large mixing bowl, combine all-purpose flour, cornstarch, garlic powder, onion powder, paprika, salt, and black pepper.</li><li>Add water gradually while whisking until you achieve a smooth batter consistency. The batter should coat the back of a spoon but still flow easily.</li><li>Heat vegetable oil in a deep frying pan or pot over medium-high heat.</li><li>Dip cauliflower florets into the batter, ensuring they are fully coated.</li><li>Carefully place the battered cauliflower florets into the hot oil, a few pieces at a time, making sure not to overcrowd the pan.</li><li>Fry the cauliflower until golden brown and crispy, about 3-4 minutes per batch.</li><li>Use a slotted spoon to remove the fried cauliflower from the oil and transfer them to a plate lined with paper towels to drain excess oil.</li><li>Continue frying the remaining cauliflower florets in batches until all are cooked.</li><li>Serve hot fried cauliflower as a delicious appetizer or side dish with your favorite dipping sauce.</li><li>Enjoy the crispy and flavorful fried cauliflower!</li></ul>",
  },
  {
    keyword: "furandana",
    response:
      "<strong>:</strong> Furandana - Roasted Rice Snack<br><br><strong>Ingredients:</strong> raw rice grains<br><strong>The Quantity of ingredients</strong><br>Varies depending on desired amount<br><br><strong>Instructions:</strong> <br><ul style='list-style-type: disc;'><li>Wash the raw rice grains thoroughly under running water to remove any impurities.</li><li>Spread the washed rice grains evenly on a clean cloth or tray to dry them completely under the sun.</li><li>Once the rice grains are dried, heat a pan or skillet over medium heat.</li><li>Add the dried rice grains to the pan and roast them, stirring continuously, until they turn golden brown and emit a nutty aroma. Be careful not to burn them.</li><li>Remove the roasted rice grains from the pan and let them cool to room temperature.</li><li>Once cooled, transfer the roasted rice grains to a mortar and pestle or a grinder.</li><li>Grind the roasted rice grains into a coarse powder. Ensure that the texture is not too fine.</li><li>Store the Furandana in an airtight container to maintain its freshness and crunchiness.</li><li>Enjoy Furandana as a crunchy snack on its own or as a topping for various dishes. It adds a delightful texture and flavor to your favorite Nepali snacks and meals!</li></ul>",
  },
  {
    keyword: "ghee",
    response:
      "<strong>:</strong> Ghee - Clarified Butter<br><br><strong>Ingredients:</strong> unsalted butter<br><strong>The Quantity of ingredients</strong><br>Varies depending on desired amount<br><br><strong>Instructions:</strong> <br><ul style='list-style-type: disc;'><li>Start by melting unsalted butter in a heavy-bottomed saucepan or pot over low heat.</li><li>As the butter melts, it will begin to separate into three layers: foam on top, clarified butter in the middle, and milk solids at the bottom.</li><li>Skim off the foam using a spoon or ladle and discard it.</li><li>Gently simmer the clarified butter over low heat, allowing the milk solids to settle at the bottom and the water content to evaporate. This process may take 20-30 minutes.</li><li>As the butter clarifies, the color will change from golden to a rich amber hue, and the milk solids at the bottom will begin to brown slightly.</li><li>Once the clarified butter turns a clear golden color and the milk solids are lightly browned, remove the pot from the heat.</li><li>Let the clarified butter cool for a few minutes before straining it through a fine mesh strainer or cheesecloth into a clean, dry glass jar or container. This will remove any remaining milk solids and impurities.</li><li>Allow the ghee to cool completely at room temperature before sealing the jar with a tight-fitting lid.</li><li>Your homemade ghee is now ready to use! Store it in a cool, dark place or in the refrigerator for longer shelf life.</li><li>Enjoy the rich flavor and aroma of homemade ghee in your cooking and baking!</li></ul>",
  },
  {
    keyword: "haluwa",
    response:
      "<strong>:</strong> Haluwa - Nepali Sweet Confection<br><br><strong>Ingredients:</strong> semolina (sooji/rava), ghee (clarified butter), sugar, water, cardamom powder, nuts (cashews, almonds, pistachios), raisins<br><strong>The Quantity of ingredients</strong><br>1 cup semolina<br>1/2 cup ghee<br>1 cup sugar<br>2 cups water<br>1/2 teaspoon cardamom powder<br>Handful of nuts and raisins for garnish<br><br><strong>Instructions:</strong> <br><ul style='list-style-type: disc;'><li>Heat ghee in a heavy-bottomed pan or kadhai over medium heat.</li><li>Add semolina to the hot ghee and roast it, stirring continuously, until it turns golden brown and aromatic. Be careful not to burn it.</li><li>In a separate saucepan, combine sugar and water. Bring the mixture to a boil, stirring until the sugar dissolves completely.</li><li>Once the semolina is roasted and the sugar syrup is ready, carefully pour the sugar syrup into the roasted semolina while stirring continuously to prevent lumps from forming.</li><li>Add cardamom powder to the mixture for flavor and aroma.</li><li>Cook the mixture over low heat, stirring constantly, until it thickens and begins to leave the sides of the pan. This may take about 5-7 minutes.</li><li>Once the haluwa reaches the desired consistency, remove it from heat and transfer it to a serving dish.</li><li>Garnish the haluwa with chopped nuts and raisins.</li><li>Allow the haluwa to cool for a few minutes before serving.</li><li>Enjoy the delicious and aromatic haluwa as a sweet treat or dessert!</li></ul>",
  },
  {
    keyword: "jaulo",
    response:
      "<strong>:</strong> Jaulo<br><br><strong>Ingredients:</strong> 1 Cup – Red lentils or Moong Dal, 1/3 Cup – Rice, 1 or 2 Garlic cloves – finely chopped, Fresh root Ginger – Thumb size piece – finely chopped/grated, 1 teaspoon – Turmeric, 1/2 teaspoon – Garam Masala, Pinch of Cumin seeds, Salt to taste, Optional – Veg or Chicken stock, 4 – 5 Cups – Water<br><strong>The Quantity of ingredients</strong><br>Varies depending on servings<br><br><strong>Method:</strong> <br>1. Wash lentils/dal until the water runs clear (soak for about 30mins to reduce cooking time-optional).<br>2. Heat a little oil in a medium-sized pot.<br>3. Add the pinch of Cumin seeds and allow to cook for just a few seconds.<br>4. Add the garlic and ginger & soften for a minute or so.<br>5. Add lentils/dal and stir in.<br>6. Add the Turmeric and Garam Masala. Stir together to combine ingredients and cook for 30 secs.<br>7. Add the rice and again stir in.<br>8. Add 4-5 cups of water (depending on how thirsty your lentils and rice are).<br>9. Add salt to taste (about 1 teaspoon).<br>10. Add veg or chicken stock if desired.<br>11. Stir well and bring to the boil and simmer for 25 minutes or until the lentils and rice are well cooked.<br>12. Stir a few times during the cooking and add water if needed. Some people like this dish to be really thick and others prefer it to more thin, it’s up to you!<br>13. Serve hot with a lovely spoonful of natural yogurt and a sprinkling of coriander leaves. Namaste And Enjoy!",
  },
  {
    keyword: "khichdi",
    response:
      "<strong>:</strong> Khichdi<br><br><strong>Ingredients:</strong> 1 cup rice, 1/2 cup split yellow mung dal, 4 cups water, 1 tablespoon ghee or clarified butter, 1 teaspoon cumin seeds, 1 teaspoon mustard seeds, 1/2 teaspoon turmeric powder, 1/2 teaspoon asafoetida (hing), 1 inch ginger, finely chopped, 2 green chilies, chopped, Salt to taste, Fresh coriander leaves for garnish<br><strong>The Quantity of ingredients</strong><br>Varies depending on servings<br><br><strong>Instructions:</strong><br>1. Rinse the rice and mung dal together until the water runs clear. Drain and set aside.<br>2. In a pressure cooker or large pot, heat the ghee over medium heat.<br>3. Add the cumin seeds and mustard seeds. Let them splutter.<br>4. Add the turmeric powder, asafoetida, ginger, and green chilies. Saute for a minute.<br>5. Add the drained rice and mung dal to the pot. Stir well to coat the grains with the spices.<br>6. Pour in the water and add salt to taste. Stir to combine.<br>7. If using a pressure cooker, close the lid and cook for 3-4 whistles. If using a pot, cover and cook until the rice and dal are soft and mushy, stirring occasionally.<br>8. Once cooked, remove from heat and let the pressure release naturally (if using a pressure cooker).<br>9. Garnish with fresh coriander leaves and serve hot.<br>10. Khichdi can be served with yogurt, pickle, or any chutney of your choice. Enjoy this comforting and nutritious dish!",
  },
  {
    keyword: "laphing",
    response:
      "<strong>:</strong> Laphing - Spicy Mung Bean Cold Noodles<br><br><strong>Ingredients:</strong> For the Mung Bean Jelly: 200g mung bean starch, 500ml water, 1/2 teaspoon salt; For the Sauce: 2 tablespoons soy sauce, 1 tablespoon chili oil, 1 tablespoon vinegar, 1 teaspoon sugar, 1 teaspoon Sichuan pepper powder, 1 teaspoon garlic, finely chopped, 1 teaspoon ginger, finely chopped, 1/4 cup spring onions, finely chopped, 1/4 cup coriander leaves, finely chopped; Optional toppings: peanuts, sesame seeds, cucumber, bean sprouts<br><strong>The Quantity of ingredients</strong><br>Varies depending on servings<br><br><strong>Instructions:</strong><br>1. To make the Mung Bean Jelly, mix mung bean starch with water and salt in a pot. Stir until smooth.<br>2. Cook the mixture over medium heat, stirring constantly until it thickens and becomes transparent.<br>3. Pour the mixture onto a flat plate and let it cool. Once cooled, cut into strips or cubes.<br>4. To make the Sauce, mix soy sauce, chili oil, vinegar, sugar, Sichuan pepper powder, garlic, ginger, spring onions, and coriander leaves in a bowl.<br>5. Arrange the Mung Bean Jelly in serving bowls and pour the sauce over it.<br>6. Garnish with optional toppings like peanuts, sesame seeds, cucumber, and bean sprouts.<br>7. Serve cold and enjoy the spicy and refreshing flavors of Laphing!",
  },
  {
    keyword: "masyaura",
    response:
      "<strong>:</strong> Masyaura - Sun-Dried Lentil and Vegetable Nuggets<br><br><strong>Ingredients:</strong> 4 cups black lentil flour, 2 cups minced vegetables (e.g., taro, yam, colocasia leaf)<br><strong>The Quantity of ingredients</strong><br>Varies depending on servings<br><br><strong>Instructions:</strong><br>1. Place the lentil flour in a mixing bowl and add enough water to make a thick paste.<br>2. Mix in the minced vegetables.<br>3. Cover the bowl and leave it overnight. This allows the paste to absorb the moisture completely and go through slight fermentation, which gives a nice flavor to the product.<br>4. In the morning, make small balls or nuggets by using your hand and place them on a tray. Wet your hand often with water, which helps prevent the paste from sticking to your hand. Ensure that the balls do not touch each other.<br>5. Place the tray in direct sunlight to allow them to dry. It will take around three days to completely sun-dry, and it might take even longer on less sunny or cloudy days. Keep it indoors during the night to speed up the drying process.<br>6. Once they are completely dried, keep them in an airtight container and store for several months.<br>7. Enjoy the Masyaura as a nutritious and flavorful snack or as an accompaniment to meals!",
  },
  {
    keyword: "pustakari",
    response:
      "<strong>:</strong> Pustakari - Nepali Candy<br><br><strong>Ingredients:</strong> Molasses, ghee, milk, coconut, dates, nuts<br><strong>The Quantity of ingredients</strong><br>Varies depending on servings<br><br><strong>Instructions:</strong><br>1. In a saucepan, combine molasses, ghee, and milk.<br>2. Cook the mixture over medium heat, stirring constantly, until it thickens and reaches a candy-like consistency.<br>3. Once the mixture is thickened, pour it onto a greased tray or plate.<br>4. Sprinkle shredded coconut, chopped dates, and nuts over the top of the mixture.<br>5. Allow the Pustakari to cool and set completely.<br>6. Once set, cut the Pustakari into small pieces or shapes.<br>7. Store the Pustakari in an airtight container.<br>8. Enjoy the delicious Nepali candy as a sweet treat! ",
  },
  {
    keyword: "puwa",
    response:
      "<strong>:</strong> Puwa / Chamal ko Puwa - Coarsely Ground Rice Cake<br><br><strong>Ingredients:</strong> Rice (coarsely ground), water<br><strong>The Quantity of ingredients</strong><br>Varies depending on servings<br><br><strong>Instructions:</strong><br>1. Rinse the coarsely ground rice thoroughly under cold water to remove any debris.<br>2. Place the rice in a large bowl and cover it with water. Let it soak for at least 6 hours or overnight.<br>3. After soaking, drain the water from the rice.<br>4. Transfer the soaked rice to a blender or food processor.<br>5. Blend the rice, adding a little water at a time, until it forms a thick batter-like consistency.<br>6. Heat a non-stick pan or griddle over medium heat.<br>7. Pour a ladleful of the rice batter onto the hot pan and spread it out into a circular shape.<br>8. Cook the Puwa on one side until bubbles start to form on the surface and the edges begin to crisp up.<br>9. Flip the Puwa and cook the other side until it is golden brown and cooked through.<br>10. Repeat the process with the remaining batter.<br>11. Serve the Puwa warm with your favorite accompaniments such as ghee, sugar, or yogurt.<br>12. Enjoy this traditional Nepali delicacy as a snack or breakfast item!",
  },
  {
    keyword: "raita",
    response:
      "<strong>:</strong> Raita - Yogurt Condiment<br><br><strong>Ingredients:</strong> Yogurt, cucumber (grated or chopped), tomatoes (diced), onion (finely chopped), cilantro (chopped), roasted cumin powder, salt, black pepper, mint leaves (optional)<br><strong>The Quantity of ingredients</strong><br>Varies depending on servings<br><br><strong>Instructions:</strong><br>1. In a mixing bowl, whisk the yogurt until smooth and creamy.<br>2. Add the grated or chopped cucumber, diced tomatoes, finely chopped onion, and chopped cilantro to the yogurt.<br>3. Season the mixture with roasted cumin powder, salt, and black pepper according to taste.<br>4. Gently mix all the ingredients until well combined.<br>5. Garnish with fresh mint leaves (optional) for added flavor.<br>6. Chill the Raita in the refrigerator for at least 30 minutes before serving to allow the flavors to meld together.<br>7. Serve chilled Raita as a refreshing side dish or accompaniment to spicy Indian or Nepali dishes.<br>8. Enjoy the cool and tangy flavors of homemade Raita!",
  },
  {
    keyword: "saag",
    response:
      "<strong>:</strong> Saag - Leafy Greens Curry<br><br><strong>Ingredients:</strong> Mixed leafy greens (spinach, mustard greens, collard greens, kale, etc.), onion (chopped), garlic (minced), ginger (grated), green chilies (chopped), tomatoes (diced), vegetable oil or ghee, cumin seeds, turmeric powder, coriander powder, red chili powder, salt, water<br><strong>The Quantity of ingredients</strong><br>Varies depending on servings<br><br><strong>Instructions:</strong><br>1. Clean and wash the mixed leafy greens thoroughly. Remove any tough stems and chop the greens roughly.<br>2. Heat oil or ghee in a large pot or pan over medium heat.<br>3. Add cumin seeds and let them splutter.<br>4. Add chopped onion, minced garlic, grated ginger, and chopped green chilies to the pot. Saute until the onions turn golden brown.<br>5. Add diced tomatoes to the pot and cook until they become soft and mushy.<br>6. Add turmeric powder, coriander powder, and red chili powder to the pot. Stir well to combine the spices with the onion-tomato mixture.<br>7. Add the chopped mixed leafy greens to the pot. Mix well with the onion-tomato-spice mixture.<br>8. Season with salt according to taste.<br>9. Add a little water to the pot to create some steam and cover the pot with a lid.<br>10. Allow the Saag to cook on low to medium heat for about 15-20 minutes, or until the greens are tender and cooked through.<br>11. Stir occasionally and add more water if necessary to prevent sticking.<br>12. Once the Saag is cooked, mash it slightly with the back of a spoon to achieve a semi-smooth consistency.<br>13. Serve hot Saag with roti, naan, or rice. Enjoy the nutritious and flavorful leafy greens curry!",
  },
  {
    keyword: "saatu",
    response:
      "<strong>:</strong> Saatu - Roasted Barley Flour<br><br><strong>Ingredients:</strong> Barley grains<br><strong>The Quantity of ingredients</strong><br>Varies depending on servings<br><br><strong>Instructions:</strong><br>1. Clean and wash the barley grains thoroughly to remove any debris or impurities.<br>2. Spread the cleaned barley grains evenly on a clean cloth or tray to dry under the sun for a few hours.<br>3. Once the barley grains are completely dry, roast them in a heavy-bottomed pan or skillet over medium heat.<br>4. Stir the barley grains frequently to ensure even roasting and prevent burning.<br>5. Roast the barley grains until they turn golden brown and emit a nutty aroma. This process may take about 15-20 minutes.<br>6. Once roasted, remove the barley grains from the heat and allow them to cool completely.<br>7. Transfer the cooled barley grains to a grinder or food processor.<br>8. Grind the roasted barley grains into a fine powder or flour consistency.<br>9. Store the Saatu (roasted barley flour) in an airtight container in a cool, dry place.<br>10. Use Saatu as a nutritious and versatile ingredient in various recipes such as porridge, bread, pancakes, or as a thickening agent in soups and stews.<br>11. Enjoy the wholesome goodness of homemade Saatu in your favorite dishes!",
  },
  {
    keyword: "sidra",
    response:
      "<strong>:</strong> Sidra Dried Small Fish - Traditional Nepali Ingredient<br><br><strong>Ingredients:</strong> Small fish (typically anchovies or similar varieties)<br><strong>The Quantity of ingredients</strong><br>Varies depending on servings<br><br><strong>Instructions:</strong><br>1. Clean and gut the small fish, removing any scales and innards.<br>2. Rinse the fish under cold water to remove any remaining debris.<br>3. Pat the fish dry with paper towels to remove excess moisture.<br>4. Arrange the cleaned fish on a drying rack or tray in a single layer.<br>5. Place the drying rack or tray in a well-ventilated area with ample sunlight.<br>6. Allow the fish to dry completely under the sun, turning them occasionally to ensure even drying.<br>7. Depending on weather conditions, drying may take several days to a week.<br>8. Once the fish are fully dried and hardened, they can be stored in an airtight container.<br>9. To use dried small fish in cooking, soak them in water for some time to soften them before incorporating them into recipes.<br>10. Dried small fish are commonly used to add flavor and protein to lentil soups, vegetable curries, and rice dishes in Nepali cuisine.<br>11. Enjoy the rich umami flavor and nutritional benefits of dried small fish in traditional Nepali dishes!",
  },
  {
    keyword: "thali",
    response:
      "<strong>:</strong> Thali - Traditional Nepali Meal Platter<br><br><strong>Ingredients:</strong> A variety of dishes including rice, lentils (dal), vegetables (sabzi), pickles (achaar), chutneys, yogurt (dahi), bread (roti or naan), papadum, dessert (mithai), and sometimes non-vegetarian items like chicken or goat curry.<br><strong>The Quantity of ingredients</strong><br>Varies depending on servings and dishes included<br><br><strong>Instructions:</strong><br>1. Prepare a selection of dishes including rice, lentils, vegetables, pickles, chutneys, yogurt, bread, papadum, dessert, and optionally non-vegetarian items.<br>2. Each dish can be prepared according to its specific recipe, using traditional Nepali spices and cooking techniques.<br>3. Arrange the dishes on a large platter or individual serving plates, keeping each dish separate from the others.<br>4. Serve the Thali with accompaniments such as water, buttermilk (chaas), or traditional beverages like lassi or chai.<br>5. To enjoy the Thali, diners typically start by mixing rice with dal and then pairing it with various vegetable dishes, pickles, and chutneys.<br>6. Bread or papadum can be enjoyed on the side or used to scoop up the main dishes.<br>7. Non-vegetarian items, if included, can be enjoyed alongside the vegetarian dishes or as a separate course.<br>8. Finish the meal with a serving of dessert or mithai.<br>9. Thali is often served during special occasions, festivals, and celebrations, offering a complete and satisfying meal experience.<br>10. Enjoy the diverse flavors and textures of a traditional Nepali Thali!",
  },
  {
    keyword: "tongba",
    response:
      "<strong>:</strong> Tongba - Traditional Millet-Based Himalayan Drink<br><br><strong>Ingredients:</strong> Fermented millet grains (typically finger millet or foxtail millet), hot water<br><strong>The Quantity of ingredients</strong><br>Varies depending on servings<br><br><strong>Instructions:</strong><br>1. Start by placing fermented millet grains in a special vessel called a Tongba or Dhungro.<br>2. Pour hot water over the fermented millet grains, filling the vessel to the brim.<br>3. Allow the millet grains to steep in the hot water for several minutes to release their flavors and nutrients.<br>4. Using a special bamboo or wooden straw with a sieve at the end, slowly sip the Tongba from the vessel, allowing the straw to filter out the grains.<br>5. As you sip, refill the vessel with hot water to continue enjoying the drink.<br>6. Tongba is typically enjoyed in a communal setting, with friends and family sharing the vessel and passing it around.<br>7. The drink is known for its warming and comforting properties, making it especially popular during cold Himalayan winters.<br>8. Enjoy the unique and traditional flavors of Tongba as you savor this beloved Himalayan beverage!",
  },
  {
    keyword: "mohi",
    response:
      "<strong>:</strong> Mohi - Buttermilk<br><br><strong>Ingredients:</strong> Yogurt, water, salt, cumin powder, mint leaves (optional)<br><strong>The Quantity of ingredients</strong><br>Varies depending on servings<br><br><strong>Instructions:</strong><br>1. In a mixing bowl, combine yogurt and water in the desired ratio to achieve the desired consistency for buttermilk.<br>2. Whisk the yogurt-water mixture until smooth and well-blended.<br>3. Add salt to taste and continue whisking to incorporate the salt into the buttermilk.<br>4. Optionally, add a pinch of cumin powder for flavor enhancement. Mix well.<br>5. If desired, garnish the Mohi with fresh mint leaves for added freshness.<br>6. Refrigerate the Mohi for a short while to chill it before serving.<br>7. Serve the refreshing Mohi as a cooling beverage, especially during hot weather or as a complement to spicy meals.<br>8. Enjoy the tangy and cooling flavors of homemade Mohi!",
  },
  {
    keyword: "tama",
    response:
      "<strong>:</strong> Tama - Fermented Bamboo Shoots<br><br><strong>Ingredients:</strong> Bamboo shoots, water, salt<br><strong>The Quantity of ingredients</strong><br>Varies depending on servings<br><br><strong>Instructions:</strong><br>1. Clean the bamboo shoots thoroughly to remove any dirt or debris.<br>2. Cut the bamboo shoots into desired sizes or slices.<br>3. In a large pot, bring water to a boil.<br>4. Add the bamboo shoots to the boiling water.<br>5. Boil the bamboo shoots for about 10-15 minutes to remove bitterness and soften them.<br>6. Drain the boiled bamboo shoots and rinse them under cold water to stop the cooking process.<br>7. Place the bamboo shoots in a clean container.<br>8. Sprinkle salt over the bamboo shoots, ensuring they are evenly coated.<br>9. Tightly close the container and let it sit at room temperature for 2-3 days to ferment.<br>10. Check the bamboo shoots periodically during the fermentation process and stir if necessary.<br>11. Once the bamboo shoots have fermented to your desired taste, they are ready to be used in various recipes.<br>12. Fermented bamboo shoots or Tama can be used in traditional Nepali dishes such as Tama Bodi, Tama Aloo, or Tama Curry.<br>13. Enjoy the unique flavor and texture of homemade Tama in your favorite Nepali recipes!",
  },
];

export default keywordResponses;
